# Generated by Django 4.0.2 on 2022-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='fname',
            new_name='name',
        ),
    ]
